### ISSUE TITLE
Environment objects do not have nav mesh blockers (AI phase through them)

### ISSUE THREAD

**Issue by nbaggett** [westonleavitt/LostIsleBugTracker#281]
solution below

**Comment by westonleavitt** [comment]
@nbaggett can we add solution to harvestables have nav mesh blockers -- have them default off (and never turn on for client) but turn on for server -- that way we prevent the navmesh recalculation as players move around since navmesh doesnt matter on client anyway.

Then apply the solution to the following:

Trees:
![image](https://github.com/user-attachments/assets/36253d69-5a36-456a-ac40-c5e64005009d)

Rocks:
![image](https://github.com/user-attachments/assets/8ffef1a4-0ab6-447e-a682-43b7b0781699)

Shards:
![image](https://github.com/user-attachments/assets/e6ff8a54-ca62-408a-9c78-17732792fc86)
