### ISSUE TITLE
The lists of building parts and objects despawning after exiting play mode are deallocating, throwing errors

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#524]
### What happened?

...

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Enter play mode. Add building parts. Exit play mode.

**Comment by tykennington** [comment]
![error](https://github.com/user-attachments/assets/fd70f93d-db50-439b-bd3c-b7629cb1f15a)
Attaching console error for reference

**Comment by tykennington** [comment]
I may need help with this one, because my previous solution attempts didn't actually work. The error only happens when there is a supply barrel built, because it tries to recalculate the upkeep when the supply barrel is removed.

NetworkManager.ShutdownInProgress is still false in the OnNetworkSpawn of WunderBuildingPartStats. This also happens before the Application.quitting event, so that can't be used either.

The null reference is on the BehaviourUpdater (which is internal) on the NetworkManager.  So there's not really a way I found to check the right thing for nulls or to check if this is exiting the game as opposed to normal despawning.

**Comment by westonleavitt** [comment]
I'm game to close this. its an after shutdown error that would realistically never cause issues for a client or a server
