### ISSUE TITLE
Sanity UI fixes

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#537]
![image](https://github.com/user-attachments/assets/063f2f2d-68db-4288-b4c7-ef852ed84dba)
- Values don't match after equipping bone armor that gives bonus max sanity
- Change icons
- Change debuff name and add description
- Only display Sanity as a debuff/status effect when the player is inside a Sanity Volume and either actively losing sanity or sanity is <100

**Comment by tykennington** [comment]
Removed the redundant sanity indicator because there's another one that already works as expected, and I updated that one's icon.
The sanity system still needs to be reworked to change the max sanity stat to an insanity resistance (and keep the max at 100), but that's a different issue, so I'm going to close this one.
