### ISSUE TITLE
Permanent alerts for stamina / deydration etc.

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#541]
dehydrating and stamina alerts permanently stay, they should pop up and out like other alerts.

![image](https://github.com/user-attachments/assets/7ed090dc-1d71-48b5-bb7d-f61846c8569b)

**Comment by tykennington** [comment]
- Alerts last 5 seconds before fading.
- The requirement said to display an alert every 5 seconds
- To prevent spamming the alerts, identical alerts just start the time on the existing alert  (and flash red) instead of making a new one.

If we don't want dehydrating and stamina alerts to be permanant we need to shorten the alert lifetime, lengthen the time between alerts, or allow duplicate alerts again.

**Comment by westonleavitt** [comment]
@tykennington that makes sense. can we try making the alerts every 15s isntead of every 5

**Comment by tykennington** [comment]
Switched alerts for famished, parched, starving, and dehydrated to every 15 seconds,
commit 510f49c7d21426e7fcc973bf867a90d6945b96dc
