### ISSUE TITLE
Research top tabs have an issue with their click timer.

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#545]
if your click is not very fast, i.e. you hold the mouse down for like .5s instead of intant click, the click doesnt trigger on the tags. 

![image](https://github.com/user-attachments/assets/c124ec41-1480-416b-b0a0-0e7cacd93ed2)

Lets just make it if your click releases on the top tabs, regardless of time to trigger the click. or something similar to fix this. It shouldn't be so agressive. 

This same thing exists for these buttons:
![image](https://github.com/user-attachments/assets/0af1cac1-90dc-43ad-aaca-69b0c38ca78b)

please fix there as well

**Comment by tykennington** [comment]
Commit ec8c2062b64637245188073541305cb2106432dc

I added an option to CustomButton.cs to register on a mouse press instead of a mouse release, or on a mouse release but ignoring the expiration time. I set the top menu buttons to select on mouse press.

I'm not sure why there's an expiration anyway. All other custom buttons right now would have the same 0.2 second window before the click expires. I left it that way for other buttons in case there's a reason for it. Otherwise, I could just switch on mouse press as the default on all of them.
