### ISSUE TITLE
Blue tinted sprint / status container?

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#552]
why are these tinted blue on the outside?

![image](https://github.com/user-attachments/assets/4040efee-c49f-4d59-b0d1-a4049c82037c)

the inside fill should be colored, but the container should be colorless

**Comment by tykennington** [comment]
Right now it's set up so that these value bars can be green for positive (buffs), red for negative (debuffs), or blue for neutral.
Stamina was a neutral bar, and it was changing the wrong thing to blue. That's fixed now, and the border is now colorless. I also switched stamina to be positive/green. I think it makes more sense as neutral though (If we want a neutral color and don't want stamina, oxygen, etc to all be green instead). Or maybe start green or blue, and then turn red when it's depleted and you can no longer run.
