### ISSUE TITLE
NPCs generating with no loot

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#560]
Add 4 npc spawns to an empty scene and enter play mode.. no error is received but none of them generate loot.

I did notice these are all missing:
![image](https://github.com/user-attachments/assets/385213c5-234d-491e-8d0b-78418cb06ded)

I also noticed the loottable is also referenced on the NPC scriptable
![image](https://github.com/user-attachments/assets/fa8d4fa4-7a10-4dc0-82c1-04fed0ac9dba)

can we:

1. Fix whatever is causing the loot to generate
2. fix in code why we are referencing this in two places
3. Add to NPC Validator conditions to prevent this from not being set or generating loot in the future

**Comment by tykennington** [comment]
That BuyNPCAction SO was left over from an old system and wasn't actually removed, so I just removed it. The ScriptableNPC has the loot table reference that is actually used.

The NPCs aren't generating any loot because the odds on every item on every NPC loot table got set to zero somehow.

![npc_spawn_odds](https://github.com/user-attachments/assets/a9889b08-1ef5-4b4f-b415-093df4ecf9e6)

**Comment by westonleavitt** [comment]
fixed
