### ISSUE TITLE
research labels clicking need delay treatment

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#584]
these are back to having the delay click issue? Is this getting reverted? I thought we fixed it

![image](https://github.com/user-attachments/assets/46749c86-35d9-4e49-b913-f9b64d636ded)

**Comment by tykennington** [comment]
I disabled the click expiration on the top nav menu, not anywhere else like in submenus. There's a "Click Type" field on the CustomButton to switch any button over.

But would we ever _want_ button clicks to expire? If not, I can just remove that bit of code and make ever button work on click instead of release (It's simpler anyway). I just left on release expiration as the default because having button clicks expire after 0.2 seconds looked like an intentional choice in the code and wasn't sure if we were relying on that for anything.

**Comment by tykennington** [comment]
I just went ahead and made all custom buttons on click, since I couldn't figure out a point to the click expiration.

commit efcfc05ea036064ae4e89a771211ce75c42fae01
