### ISSUE TITLE
Dig SFX desynced from impact VFX

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#609]
https://streamable.com/2hjzp6
The SFX is delayed and plays noticeably later than the impact VFX - need them to happen at the same time

**Comment by tykennington** [comment]
Fixed by starting the the SFX a little before the VFX. If this needs to be adjusted again, there's a "Time Between SFX and VFX" field on the Dig Manager. It's currently set to 0.15, which seemed to line them up well to my ear.
But I did notice of the 5 random dig sounds, some of them have a little bit more leading time than others. So those files could be trimmed if the 0.15 second adjustment for all of them wasn't exact enough.
