### ISSUE TITLE
Anvil deployment limitations too restrictive

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#653]
Unable to place the anvil in areas where it looks like it should be able to be placed.
https://streamable.com/h7hies

**Comment by tykennington** [comment]
commit 5de51ca

This was because of that separation condition we had on deployables that could spawn NPCs (so we don't crowd too many in one area). Since we disabled inviting NPCs to your base for now, I went ahead and disabled that build condition as well, allowing anvils to be placed next to fireplaces etc. But we may need to revisit how we want to handle giving NPCs space when we add npc invitations back in.
