### ISSUE TITLE
Unarmed state breaks after throwing item

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#659]
After throwing the item you're currently holding your character switches back to the default unarmed state but it doesn't allow you to harvest or deal damage. The unarmed state after manually unequipping an item works fine, but it breaks after throwing your currently equipped item.
https://streamable.com/pgngpw

**Comment by nbaggett** [comment]
fixed in latest

something to note @tykennington @westonleavitt the remove item code sets the slot to new ItemInstance(0) when the quantity is set to 0, which is considered different than unarmed which lets you swap to the same slot after throwing the item. So you can switch to the same hotbar item. The issue ended up being a check if the current equipped item instance was null rather than the iteminstance.item so now it checks for both for harvesting but it may be something to look at
