### ISSUE TITLE
Tooltips again blending with UI, on top/behind stats, etc

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#685]
connect to server in steam, open invneotyr and scroll over an item that puts the tooltip behind the stats panel

**Comment by tykennington** [comment]
Fixed in commit 62b2789

The issue was that two canvases had the same sort order, and apparently the build decides to break the tie differently from the editor (although I was able to recreate the issue in the editor by disabling and reenabling one of the canvases). I resolved it by incrementing the sort order of the canvas with the tooltip by 1.
